
-- liquibase formatted sql
-- changeset genrietta:create-users-table1

CREATE TABLE IF NOT EXISTS "users" (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       password VARCHAR(80) NOT NULL,
                       username VARCHAR(40) NOT NULL UNIQUE
);

-- liquibase formatted sql
-- changeset genrietta:create-user-folder-table1

CREATE TABLE IF NOT EXISTS "user_folder" (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       user_id BIGINT REFERENCES "users"(id)
    );